version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: "lockfile-only"
    groups:
      lockfile:
        patterns:
          - "*"
