name: test-generate-bundles

on:
  pull_request:
    branches: [main]
    paths:
      - scripts/**
      - yarn.lock

jobs:
  test-generate-bundles:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-buildx-action@v3
      - name: build docker image
        uses: docker/build-push-action@v6
        with:
          context: scripts
          load: true
          tags: generate-bundles
          cache-from: type=gha,scope=${{ hashFiles('yarn.lock') }}
          cache-to: type=gha,mode=max,scope=${{ hashFiles('yarn.lock') }}
      - name: test generate bundles
        run: sh scripts/generateBundles.sh --skip-build
      - name: check for changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Error: Files were modified or added"
            git status
            git diff
            exit 1
          fi
